### ISSUE TITLE
Few error points causes strange error bar

### ISSUE THREAD

**Issue by jon-modelon** [modelica-tools/csv-compare#11]
First of, the new version of CSV compare is much better!

The behaviour for the error graph has changed since previous versions of csv-compare (pre 2.0?).
Now it only plot the graph for the part that has an error.
I don't know if this is intended or not but it causes problems when there's only a one or two error points:
![fig1](https://cloud.githubusercontent.com/assets/3479182/6747317/db66a7f2-ced7-11e4-9504-87e7e7168453.png)
![fig2](https://cloud.githubusercontent.com/assets/3479182/6747318/db674cc0-ced7-11e4-9b0f-1dd7a2375e20.png)

All files that was used can be found [here](https://gist.github.com/jon-modelon/0dfea1666d90db020ca7), and the command was:

> Compare.exe -o -m csvFileCompare -r . -t 0.001 --inlineactual.csv target.csv
>2015-03-20Z07:53:27 [     Warning ] aimc.idq_rr[2] is invalid! 1 errors have been found during validation.
>2015-03-20Z07:53:27 [     Warning ] aimc.idq_rr[1] is invalid! 2 errors have been found during validation.
>2015-03-20Z07:53:27 [     Warning ] aimc.idq_sr[1] is invalid! 1 errors have been found during validation.

Version:
> Compare.exe --help
>CSV File Comparison Tool 2.0.0.1
>Copyright Â©  2015 - ITI GmbH

It would be really nice if the two graphs was synced, so if you zoomed in one, the other one was zoomed as well, in x-axis that is.

**Comment by jon-modelon** [comment]
There also seems to be problems with the error bar if there are multiple errors in the same trajectory but there are correct points between the erroneous ones. The error graph does not return to zero for the correct points.

The problem seems to be that the the javascript vector data_err is only populated with the failing points.

>var data_err = [[[0.13429982603224,1.97700897048878],[0.13429982603224,1.97700897048878],[0.134347309398613,1.46551025424518],[0.134347309398613,1.46551025424518],[0.758947936283575,0.407209079166],[0.758947936283575,0.407209079166],[0.758948050028233,0.40808983935079],[0.758948050028233,0.40808983935079],[0.846758735652558,0.667968759364092],[0.846758735652558,0.667968759364092],[0.846758874695406,0.673981025204942],[0.846758874695406,0.673981025204942]]];

**Comment by svenruetz** [comment]
The behaviour is not intended, but the new tube algorithm returns only the errors at the invalid points. I am going to fill the list with zeros in the valid parts

**Comment by jon-modelon** [comment]
Ok, sounds great :)

**Comment by jon-modelon** [comment]
Thanks
