### ISSUE TITLE
Missing variables causes crash

### ISSUE THREAD

**Issue by jon-modelon** [modelica-tools/csv-compare#3]
Since r8061 (on the MA svn) we get the following errors when a variable is missing in the result file.
Command used is 
>Compare.exe -o -m csvFileCompare res.csv base.csv

Output is:
>2015-01-23Z15:02:43 [     Warning ] No report directory has been set, using ""
>2015-01-23Z15:02:43 [     Warning ] actuator.armature.mass.der(s) not found in "
>C:\Users\jon_041\Downloads\res.csv", skipping checks.
>2015-01-23Z15:02:43 [       Error ] Exception during run: Object reference not set to an instance of an object.
>CSV File Comparison Tool 2.0.0.8061
>Copyright ©  2014 - ITI GmbH
>
>This software is free software and released under The BSD 3-Clause License
>...

**Comment by jon-modelon** [comment]
Files:
https://gist.github.com/jon-modelon/4b6de7fe53a7f4337e20

**Comment by svenruetz** [comment]
I checked with the current development version and it works. The svn repository of csv-compare will not be changed. All development happens here. The issue is fixed in current "regression-test-changes" branch and will be fixed in "master" after merging.

I can send you a prebuilt beta if you need one.

**Comment by jon-modelon** [comment]
@svenruetz Ok great, please, send me a prebuilt beta and I will test it :)

**Comment by svenruetz** [comment]
please use this for testing:
https://github.com/modelica-tools/csv-compare/releases/tag/2.0.0

**Comment by jon-modelon** [comment]
That version solves this issue. Thanks :+1:
