### ISSUE TITLE
Incorrect handling of result points at the same timepoint

### ISSUE THREAD

**Issue by jon-modelon** [modelica-tools/csv-compare#4]
We previously created [this ticket](https://trac.modelica.org/Modelica/ticket/1642). It was fixed with the new algorithm. However we still see some odd behaviours, probably related to input handling.
![fig](https://cloud.githubusercontent.com/assets/3479182/5901200/df821fb4-a570-11e4-8527-3261c44bccac.png)
If you check the result points you see that the result points at t = 0.1 has been swapped.

Both the base and result has been swapped in the example above, however there are other places in that signal where only the result is swapped, t=~0.148, t=~0.1965, t=~2446, etc.

Command:
>Compare.exe -o -m csvFileCompare -d , actual.csv expected.csv
Files can be found [here](https://gist.github.com/jon-modelon/056c1e6d31d1fdcfb89a)
This was found using [this version](https://github.com/modelica-tools/csv-compare/releases/tag/2.0.0)

**Comment by svenruetz** [comment]
In my development version (should be the same I uploaded) it looks like this:
![report 26 01](https://cloud.githubusercontent.com/assets/10610821/5902692/ddef337e-a57c-11e4-8e1f-d0d589cc449b.png)
I used your files and your commandline

**Comment by jon-modelon** [comment]
I've tested with both the 32bit and 64bit versions from [here](https://github.com/modelica-tools/csv-compare/releases/tag/2.0.0).
I get the following version information if I run without arguments, notice that it says 2.0.0.1:
>CSV File Comparison Tool 2.0.0.1
>Copyright ©  2015 - ITI GmbH

**Comment by svenruetz** [comment]
This is really weird, I even downloaded the zips and tried them and I cannot reproduce your plot. I even changed my system settings to swedish :)

Can you send me the report html files so I can check the arrays in the javascript part of the report.

**Comment by jon-modelon** [comment]
Ok so I'm pretty sure that this is browser/jqplot related. I get this in IE 11.0.9600.17420:
![ie fig](https://cloud.githubusercontent.com/assets/3479182/5916590/1d4af85a-a613-11e4-9796-9a574db6f13b.png)
The image above was rendered using Chrome 39.0.2171.95 m
I've uploaded the html file [here](https://gist.github.com/jon-modelon/056c1e6d31d1fdcfb89a)

**Comment by svenruetz** [comment]
Jep. Browser issue, I can reproduce in current IE and Chrome. As it is "only" a plotting error I'll try to update the jqplot lib to a current version; hopefully this will fix the problem

**Comment by svenruetz** [comment]
I updated jqplot and I found the exact value where the plotting fails in Chrome and IE but the problem is still there.

May I use the report with your csv files to file a bug at jqplot?

**Comment by jon-modelon** [comment]
Ok, sad to hear that it didn't resolve the issue.
You may use the csv files for a jqplot issue, no problem.

**Comment by svenruetz** [comment]
I created a ticket for jqplot here: https://bitbucket.org/cleonello/jqplot/issue/1013/wrong-display-of-plots-across-browsers
