### ISSUE TITLE
File remains in temporary folder after run

### ISSUE THREAD

**Issue by victorjoh** [modelica-tools/csv-compare#43]
Running Compare.exe with the following input:
```
Compare.exe -r . --override result.csv reference.csv
```
where `result.csv` contains:
```
time;x
0.0;0.0
1.0;0.0
2.0;0.0
```
and `reference.csv` contains:
```
time;x
0.0;0.0
2.0;0.0
```
will give the following output:
```
2018-04-12Z15:51:42 [     Warning ] The resolution of the base x-axis is smaller
than the compare x-axis. The better the base resolution is, the better the
validation result will be!
```
It will also generate an empty file in windows temporary folder. An example file name is: `tmpB053.tmp`

Expected behavior is to not get any file in the temporary folder.

This was found in version 2.0.0.1

**Comment by tbeu** [comment]
Hm, I cannot reproduce in with current master.

**Comment by victorjoh** [comment]
I cannot reproduce it with current master either. Closing.
