### ISSUE TITLE
csvFileCompare fails since 2.0.1

### ISSUE THREAD

**Issue by sozorn** [modelica-tools/csv-compare#55]
mode csvFileCompare compares files but before writing report the error "Paths do not have the same base" occurs even though paths are ok. Same setup with version 2.0.0 works...

**Comment by beutlich** [comment]
[More details please such that I can easily reproduce.](http://sscce.org/)

**Comment by sozorn** [comment]
Compare.exe --mode csvFileCompare --reportdir "iiwa14\reports" --tolerance 0.1 "iiwa14_compare.csv" "iiwa14_reference.csv" -d , -l "iiwa14\logs\logfile.txt" 
![output](https://user-images.githubusercontent.com/49435159/55792341-b0ec2f00-5ac0-11e9-84ec-c281a7a3c9d1.png)

**Comment by beutlich** [comment]
Can you please attach the two CSV files here.

**Comment by sozorn** [comment]
![output2](https://user-images.githubusercontent.com/49435159/55798708-ee0bed80-5acf-11e9-8d67-8a3f4771c62e.png)
had to rename to txt since no csv upload is supported...  
[compare.txt](https://github.com/modelica-tools/csv-compare/files/3058806/compare.txt)
[reference.txt](https://github.com/modelica-tools/csv-compare/files/3058807/reference.txt)

**Comment by sozorn** [comment]
when using same data in mode csvTreeCompare it works fine

**Comment by beutlich** [comment]
Hm, still cannot reproduce with current master.

**Comment by sozorn** [comment]
Ok, thanks. We build from master and it has the same error and also tried on a different system win10 x64. Could you maybe try with the release 2.0.1 to reproduce?

**Comment by beutlich** [comment]
Can reproduce with relative pathes. Will provide a fix and new release soon.

**Comment by beutlich** [comment]
@sozorn Does it work out for you now? Still waiting for some confirmation before preparing the new release.

**Comment by sozorn** [comment]
Yes it does. Thanks a lot!
