### ISSUE TITLE
Issues with updated tube width logic

### ISSUE THREAD

**Issue by casella** [modelica-tools/csv-compare#74]
Matthias Schaefer reports that as LTX started to use the updated CSV-compare tool (commit 6c456d6a) on their servers, they started to get worse results in many cases that were previously working fine.

One such case is [ModelicaTest.Fluid.Dissipation.TestCases.PressureLoss.Bend](https://www.ltx.de/download/MA/Compare_MSL_v4.1.0/Compare/ModelicaTest/20240925003601/ModelicaTest.Fluid.Dissipation.TestCases.PressureLoss.Bend/CSVCompare/Bend_report.html#a722b3ec0-87de-4c06-b061-24eb89c400cd). If you check the linked test report for variable `result.IN_p.ports[1].h_outflow`, there is a constant reference value of 293586.68524, with an upper and lower tube that are apparently giving a relative tolerance of 1e-12.

My original commit 18a20316 only tweaked the computation of baseY by replacing epsilon = 1e-12 with default_nominal = 0.001 in case both the minimum value of the reference signal and the difference between the minimum and the maximum were very small or zero. As far as I understand, that should not have caused such a problem. I'll have Matthias check with that commit, just in case.

@beutlich, after that commit, you applied several refactoring commits. Maybe something went wrong there? Could you please check with the above-mentioned test case?

Thanks!

**Comment by casella** [comment]
Keeping @GallLeo in the loop.

**Comment by beutlich** [comment]
Thanks for reporting. As stated [here](https://github.com/modelica-tools/csv-compare/pull/73#issuecomment-2374486653), such regressions are rather expected due to insufficient testing. 

#75 addresses two of the found regressions.
